# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Iacovos G. Kolokasis
title: PhD Student
email: kolokasis@ics.forth.gr
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: jackkolokasis.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  jackkolokasis
linkedin_username: jackkolokasis
twitter_username: jackkolokasis
googlescholar_username: _0dqjVAAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/kolokasis.jpg
about_content: | # this will include new lines to allow paragraphs

  I am a 3rd-year PhD student in the <a href="www.csd.uoc.gr">Computer Science Department at the
  University of Crete</a>, working with <a href="https://users.ics.forth.gr/~bilas">Prof. Angelos Bilas</a>. 
  I am also a graduate research assistant in the <a
  href="https://www.ics.forth.gr/carv/">Institute of Computer Science (ICS)</a> 
  at the <a href="https://www.forth.gr/">Foundation of Research and Technology -
  Hellas (FORTH)</a>. I received my Bachelor’s and Master’s degrees in Computer
  Science from the University of Crete in 2017 and 2020, respectively. My main
  research interests fall at the intersection of managed programming languages
  and runtimes, memory, and storage systems. My work focuses on exploiting
  emerging non-volatile memories and fast block-addressable storage devices to
  improve heap efficiency in managed languages for data warehouse workloads,
  such as big-data analytics frameworks. My recent work resolves the tension
  between garbage collection and serialization/deserialization by providing a
  separate scanless managed heap over storage devices. It eliminates both
  garbage collection and serialization overheads without imposing any language
  restrictions.  

  I am honored that my current work, during my doctoral studies, was awarded with the 
  <a href="https://research.facebook.com/fellows/kolokasis-iacovos-g/">Meta Research PhD Fellowship (2022-2024)</a> and the <a href="https://www.cyscholarships.gov.cy/">State Scholarship Foundation of Cyprus (2020-2023).</a>

  <img src="https://img.shields.io/badge/Interests-Managed Languages and Runtimes, Garbage Collection, Memory Systems-dodgerblue" />

  <a href="cv.pdf" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/Click for CV-critical" /></a>

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                    # other value (or no value) means no border will be displayed
  #      title: Project name
  #      link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      link_text: Link Text
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  #- title: Experience
  #  layout: list
  #  content:
  #    - layout: right
  #      title: Company name
  #      sub_title: Job title
  #      caption: Date Range (eg. November 2016 - present)
  #      link: Link to company (optional)
  #      quote: >
  #        Short description of the company (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description of role
  - title: Experience
    layout: list
    content:
      - layout: top
        title: CARV, ICS-FORTH
        sub_title: Graduate Research Assistant
        caption: Sep. 2017 - present · Heraklion, Greece
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/forth.png" alt="UoC logo" height="50"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/forth.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/forth.png" alt="UoC logo" height="60"/> 
          </div>
      - layout: top
        title: Huawei Research Center
        sub_title: Intern Research Student
        caption: Jun. 2022 - Sep. 2022 · Munich, Gernamy
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/huawei.png" alt="UoC logo" height="50"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/huawei.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/huawei.png" alt="UoC logo" height="60"/> 
          </div>
      - layout: top
        title: SAP
        sub_title: Intern Research Student
        caption: Jun. 2019 - Sep. 2019 · Walldorf, Gernamy
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/sap.png" alt="UoC logo" height="50"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/sap.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/sap.png" alt="UoC logo" height="60"/> 
          </div>
      - layout: top
        title: CARV, ICS-FORTH
        sub_title: Undergraduate Research Assistant
        caption: Jan. 2017 - Aug. 2017 · Heraklion, Greece
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/forth.png" alt="UoC logo" height="50"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/forth.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/forth.png" alt="UoC logo" height="60"/> 
          </div>
  - title: Education
    layout: list
    content:
      - layout: top
        title: University of Crete, Greece
        sub_title: Ph.D., Computer Science
        caption: |
          2020 - present
          <br>
          Supervisor: Angelos Bilas
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/uoc.png" alt="UoC logo" height="85"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/uoc.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/uoc.png" alt="UoC logo" height="60"/> 
          </div>

      - layout: top
        title: University of Crete, Greece
        sub_title: M.Sc., Computer Science
        caption: |
          2017 - 2020
          <br>
          Dissertation: <em><a href="https://elocus.lib.uoc.gr/dlib/5/5/1/attached-metadata-dlib-1617101997-352719-7563/Thesis_Kolokasis_Iakwvos.pdf">TeraCache: Efficient Spark Caching Over Fast Storage Devices</a></em>
          <br>
          Supervisor: Polyvios Pratikakis and Angelos Bilas
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/uoc.png" alt="UoC logo" height="85"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/uoc.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/uoc.png" alt="UoC logo" height="60"/> 
          </div>
      - layout: top
        title: University of Crete, Greece
        sub_title: B.Sc., Computer Science
        caption: |
          2011 - 2017
          <br>
          Disertation: Locality Optimizations Distributed Graph Analysis Computations 
          <br>
          Supervisor: Polyvios Pratikakis
        description: | # this will include new lines to allow paragraphs
          <br>
          <br>
          <div style="text-align: right; margin-top: -140px;" class="hidden-xs hidden-sm">
            <img src="images/uoc.png" alt="UoC logo" height="85"/> 
          </div>
          <div style="text-align: right; margin-top: -150px;" class="visible-sm-block">
            <img src="images/uoc.png" alt="UoC logo" height="60"/> 
          </div>
          <div style="text-align: center; " class="visible-xs-block">
            <img src="images/uoc.png" alt="UoC logo" height="60"/> 
          </div>
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: "TeraHeap: Reducing Memory Pressure in Managed Big Data Frameworks"
        link: https://dl.acm.org/doi/abs/10.1145/3582016.3582045
        link_text: Click for full text
        sub_title: 2023. 28th ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS '23). ACM. DOI https://doi.org/10.1145/3582016.3582045
        description: | # this will include new lines to allow paragraphs
          <b>Iacovos G. Kolokasis</b>, Giannos Evdorou, Shoaib Akram, Christos Kozanitis, Anastasios Papagiannis, Foivos S. Zakkak, Polyvios Pratikakis, and Angelos Bilas
        additional_links:
          - title: Bibtex
            icon: fa fa-book
            url: https://jackkolokasis.github.io/kolokasis.github.io/papers/teraheap.bib
          - title: Link
            icon: fa fa-paperclip
            url: https://dl.acm.org/doi/abs/10.1145/3582016.3582045
          - title: presentation
            icon: fa fa-slideshare
            url: https://jackkolokasis.github.io/kolokasis.github.io/slides/teraheap-asplos23-kolokasis.pdf
          - title: poster
            icon: fa fa-file-image-o
            url: https://jackkolokasis.github.io/kolokasis.github.io/posters/teraheap.pdf
          - title: github
            icon: fab fa-github
            url: https://github.com/jackkolokasis/teraheap
          - title: video
            icon: fa fa-video
            url: https://www.youtube.com/watch?v=2fSqvkNk07M

      - layout: top
        title: "Say Goodbye to Off-heap Caches! On-heap Caches Using Memory-Mapped I/O"
        link: https://www.usenix.org/conference/hotstorage20/presentation/kolokasis
        link_text: Click for full text
        sub_title: 2020. 12th USENIX Workshop on Hot Topics in Storage and File Systems (HotStorage 20). USENIX Association.
        description: | # this will include new lines to allow paragraphs
          <b>Iacovos G. Kolokasis</b>, Anastasios Papagiannis, Foivos S. Zakkak, Polyvios Pratikakis, and Angelos Bilas
        additional_links:
          - title: Bibtex
            icon: fa fa-book
            url: https://jackkolokasis.github.io/kolokasis.github.io/papers/teracache.bib
          - title: Link
            icon: fa fa-paperclip
            url: https://www.usenix.org/conference/hotstorage20/presentation/kolokasis
          - title: presentation
            icon: fa fa-slideshare
            url: https://jackkolokasis.github.io/kolokasis.github.io/slides/hotstorage20-paper17-slides-kolokalis.pdf
          - title: video
            icon: fa fa-video
            url: https://www.youtube.com/watch?v=rqpXpTnQxZg
      
      - layout: top
        title: "Cut to Fit: Tailoring the Partitioning to the Computation"
        link: https://dl.acm.org/doi/abs/10.1145/3327964.3328498
        link_text: Click for full text
        sub_title: 2019. 2nd Joint International Workshop on Graph Data Management Experiences & Systems (GRADES) and Network Data Analytics (NDA) (GRADES-NDA’19). ACM. DOI https://doi.org/10.1145/3327964.3328498
        description: | # this will include new lines to allow paragraphs
          <b>Iacovos G. Kolokasis</b> and Polyvios Pratikakis
        additional_links:
          - title: Bibtex
            icon: fa fa-book
            url: https://jackkolokasis.github.io/kolokasis.github.io/papers/cut_to_fit.bib
          - title: Link
            icon: fa fa-paperclip
            url: https://dl.acm.org/doi/10.1145/3327964.3328498
          - title: presentation
            icon: fa fa-slideshare
            url: https://www.slideshare.net/jackkolokasis/cut-to-fit-tailoring-the-partitioning-to-the-computation
          - title: poster
            icon: fa fa-file-image-o
            url: https://jackkolokasis.github.io/kolokasis.github.io/posters/cut_to_fit.pdf
          - title: github
            icon: fab fa-github
            url: https://github.com/jackkolokasis/graphPartitioning

  - title: Selected Talks / Posters # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: "GateKeeper: Transparent Placement of Big Data Objects in Hybrid Managed Heaps"
        link_text: Click for full text
        sub_title: 2024.  18th EuroSys Doctoral Workshop (EuroDW '24)
        additional_links:
          - title: presentation
            icon: fa fa-slideshare
            url: https://jackkolokasis.github.io/kolokasis.github.io/slides/gatekeeper_kolokasis_eurodwl.pdf

      - layout: top
        title: "DynaHeap: Dynamic Division of DRAM between Heterogeneous Managed Heaps"
        link_text: Click for full text
        sub_title: 2024.  19th European Conference on Computer Systems (EuroSys '24)  
        additional_links:
          - title: poster
            icon: fa fa-file-image-o
            url: https://jackkolokasis.github.io/kolokasis.github.io/posters/dynaheap_eurosys24.pdf
          - title: Link
            icon: fa fa-paperclip
            url: https://jackkolokasis.github.io/kolokasis.github.io/papers/dynaheap_abstract_eurosys24.pdf
      - layout: top
        title: "DynaHeap: Dynamic Division of DRAM between Heterogeneous Managed Heaps"
        link_text: Click for full text
        sub_title: 2023. 29th ACM Symposium on Operating Systems Principles (SOSP '23)  
        additional_links:
          - title: poster
            icon: fa fa-file-image-o
            url: https://jackkolokasis.github.io/kolokasis.github.io/posters/dynaheap_sosp23.pdf
          - title: Link
            icon: fa fa-paperclip
            url: https://jackkolokasis.github.io/kolokasis.github.io/papers/sosp2023-dynaheap.pdf
      - layout: top
        title: "TeraCache: Efficient Caching over Fast Storage Devices"
        link_text: Click for full text
        sub_title: 2021. MSR Cambridge PhD Virtual Workshop on Next-Generation Cloud Infrastructure
        additional_links:
          - title: poster
            icon: fa fa-file-image-o
            url: https://jackkolokasis.github.io/kolokasis.github.io/posters/teracache_msr.pdf

      - layout: top
        title: "TeraCache: Efficient Caching over Fast Storage Devices"
        link_text: Click for full text
        sub_title: 2020. Data and AI Summit Europe'20
        additional_links:
          - title: presentation
            icon: fa fa-slideshare
            url: https://jackkolokasis.github.io/kolokasis.github.io/slides/kolokasis_spark_summit_final.pdf
          - title: video
            icon: fa fa-video
            url: https://www.youtube.com/watch?v=O1PzEmUJ-X0  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
